yangwon-park/our_neighborhood

src/main/java/ywphsm/ourneighbor/controller/EditController.java, src/main/java/ywphsm/ourneighbor/controller/GoogleLoginController.java, src/main/java/ywphsm/ourneighbor/controller/HomeController.java, src/main/java/ywphsm/ourneighbor/controller/NaverLoginController.java, src/main/java/ywphsm/ourneighbor/controller/SignUpController.java, src/main/java/ywphsm/ourneighbor/controller/form/EmailConfirmForm.java, src/main/java/ywphsm/ourneighbor/controller/form/MemberForm.java, src/main/java/ywphsm/ourneighbor/domain/member/Member.java, src/main/java/ywphsm/ourneighbor/service/GoogleService.java, src/main/resources/errors.properties, src/main/resources/templates/edit/EmailConfirmForm.html, src/main/resources/templates/edit/alreadyEmailConfirm.html, src/main/resources/templates/edit/editForm.html, src/main/resources/templates/signUp/confirmEmail.html, src/main/resources/templates/signUp/emailFail.html, src/main/resources/templates/signUp/signUpForm.html
회원수정에서 이메일인증 기능, 구글 로그인시 People라이브러리 등록해서 정보받아오게 수정
이메일 토큰 시간 만료시 인증실패 페이지로 이동
=> 회원수정에서 이메일인증 기능, 구글 로그인시 People라이브러리 등록해서 정보받아오게 수정

build.gradle, src/main/java/ywphsm/ourneighbor/controller/SignUpController.java, src/main/java/ywphsm/ourneighbor/controller/findUserController.java, src/main/java/ywphsm/ourneighbor/controller/form/FindPasswordForm.java, src/main/java/ywphsm/ourneighbor/controller/form/FindUserIdForm.java, src/main/java/ywphsm/ourneighbor/controller/form/MemberForm.java, src/main/java/ywphsm/ourneighbor/controller/form/PhoneCertifiedForm.java, src/main/java/ywphsm/ourneighbor/repository/member/MemberRepository.java, src/main/java/ywphsm/ourneighbor/service/GoogleService.java, src/main/java/ywphsm/ourneighbor/service/MemberService.java, src/main/java/ywphsm/ourneighbor/service/login/SessionConst.java, src/main/resources/errors.properties, src/main/resources/templates/login/findPassword.html, src/main/resources/templates/login/findUserId.html, src/main/resources/templates/login/login.html, src/main/resources/templates/login/loginForm.html, src/main/resources/templates/signUp/certifiedPhoneForm.html, src/main/resources/templates/signUp/signUpForm.html
비밀번호(새비밀번호로 바꿔서 수정 저장, 아이디값 입력받음)
아이디찾기(이메일 입력받아서 이메일에 아이디 전송)
전화번호 문자인증(전화번호를 먼저 치고 인증번호를 날리면 회원가입 폼으로 넘어감, 억지로 회원가입폼으로 들어가면 팅굼)
=> 아이디, 비밀번호 찾기 전화번호 문자인증 

src/main/java/ywphsm/ourneighbor/domain/dto/StoreDTO.java, src/main/java/ywphsm/ourneighbor/domain/embedded/BusinessTime.java, src/main/java/ywphsm/ourneighbor/domain/store/Store.java, src/main/resources/static/css/app.css, src/main/resources/static/js/store.js, src/main/resources/templates/layout/navbar.html, src/main/resources/templates/store/add_form.html, src/main/resources/templates/store/detail.html, src/main/resources/templates/store/edit_form.html
Store Entity - homePage, lastOrder Column 추가.
이에 따른 store.add_form.html, edit_form.html, detail.html 맞춰서 수정
=> Refactor: "Store Entity Column 추가 및 Html 수정"

src/main/java/ywphsm/ourneighbor/api/MapSearchController.java, src/main/java/ywphsm/ourneighbor/api/StoreApiController.java, src/main/resources/static/js/app.js, src/main/resources/static/js/map.js, src/main/resources/static/js/weather.js, src/main/resources/templates/index.html
쿠키 expire 1년 이상으로 설정돼있는 것을 발견하여 30분으로 수정함.
현재 웹에서만 동작하는 서비스라 위치 정보는 사실 만료될 필요가 없긴
하지만, 날씨 정보는 시간에 따라 달라질 수 있으므로 쿠키 시간을 30분으로
설정했음.
=> Refactor: "쿠키 expire 시간 재설정"

src/main/java/ywphsm/ourneighbor/api/MapSearchController.java, src/main/java/ywphsm/ourneighbor/api/RecommendApiController.java, src/main/java/ywphsm/ourneighbor/controller/RecommendPostController.java, src/main/java/ywphsm/ourneighbor/controller/StoreController.java, src/main/java/ywphsm/ourneighbor/domain/RecommendPost.java, src/main/java/ywphsm/ourneighbor/domain/dto/RecommendPostDTO.java, src/main/java/ywphsm/ourneighbor/repository/recommendpost/RecommendPostRepository.java, src/main/java/ywphsm/ourneighbor/repository/recommendpost/RecommendPostRepositoryCustom.java, src/main/java/ywphsm/ourneighbor/repository/recommendpost/RecommendPostRepositoryImpl.java, src/main/java/ywphsm/ourneighbor/service/RecommendPostService.java, src/main/resources/static/js/app.js, src/main/resources/static/js/recommend_post.js, src/main/resources/templates/recommend_post/add_form.html
날씨에 맞게 추천할 수 있는 기능을 구현하기 위해, 추천 날씨 정보와 양식을
저장할 수 있는 RecommendPost Entity 생성.
이를 기반으로 홈화면에 현재 날씨를 토대로 추천 양식을 생성해줌.
현재까지 RecommendPost를 등록하는 기능까지 구현됨 (수정 및 삭제는 보류
중).
=> Feat: "RecommendPost Entity 생성 및 등록 기능 구현"

src/main/java/ywphsm/ourneighbor/api/MapSearchController.java, src/main/java/ywphsm/ourneighbor/repository/recommendpost/RecommendPostRepository.java, src/main/java/ywphsm/ourneighbor/service/RecommendPostService.java, src/main/resources/static/js/weather.js, src/main/resources/templates/index.html, src/main/resources/templates/recommend_post/add_form.html
홈화면에 뿌릴 RecommendPost 데이터: 페이징 쿼리를 활용하여 랜덤으로 하나의 데이터가 조회되게 변경. (모든 데이터를 조회한 후, 랜덤으로 추출하는 것보다 성능상 이점이 있음)
=> Refactor: "RecommendPost 페이징 기능을 통한 랜덤 조회로 변경"

src/main/java/ywphsm/ourneighbor/repository/store/dto/SimpleSearchStoreDTO.java, src/main/resources/templates/layout/footer.html
Travis CI Trial 만료로 인해 비용 발생. 생각보다 큰 비용이 부담되어
무료로 배포가 가능한 Github Actions을 선택 후, Migration 진행.
SimpleSearchStoreDTO => Store Entity 변환 시, 기존 Entity.file이 null인 경우 NPE로 인해 버그 발생하여 수정
=> Refactor: "Migrataion Travis CI to Github Actions, 매장 호출시 NPE 에러 발생 수정"

src/main/java/ywphsm/ourneighbor/controller/StoreController.java, src/main/resources/templates/store/detail.html, src/main/resources/templates/store/store_owner_edit.html
수정"
store_owner_edit.html 매핑 주소가 정해놓은 네이밍 규칙에 어긋나서 수정. detail.html 관리자 전용 버튼 및 좋아요 버튼 배열 수정 및 크기 조정.
=> Refactor: "store_owner_edit.html Mapping URL 수정, store.detail.html css

src/main/java/ywphsm/ourneighbor/repository/store/StoreRepository.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/main/java/ywphsm/ourneighbor/service/StoreService.java, src/test/java/ywphsm/ourneighbor/service/RecommendPostServiceTest.java, src/test/java/ywphsm/ourneighbor/service/StoreServiceTest.java, src/test/java/ywphsm/ourneighbor/spatial/GeolatteTest.java, src/test/java/ywphsm/ourneighbor/spatial/JTSTest.java
메소드별 설명을 위한 주석 추가 및 사용 안 하는 코드 정리와 기존 코드 좀
더 깔끔하게 리팩토링 실시.
=> Refactor: "주석 생성 및 코드 리팩토링"

src/main/resources/static/js/store.js
1. 매장 등록 시, 카테고리 리스트 출력 안 되는 버그 해결 (PR 도중 깔끔하게 Merge가 안 됐었던 거 같음.)
2. 매장 수정 시, 소분류 카테고리 초기화 안 되는 버그 해결
=> Fix: "매장 - 카테고리 연동 버그 해결'

src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/main/resources/static/js/menu.js, src/main/resources/static/js/review.js
js파일의 createDefaultImg 메소드 내의 로직을 수정하여 기본 이미지를
무조건 등록되지 않게 변경.
228
=> Fix: "메뉴, 리뷰 등록 시, 기본 이미지 무조건 등록되는 버그 해결"

src/main/java/ywphsm/ourneighbor/api/SearchController.java, src/main/java/ywphsm/ourneighbor/domain/store/distance/Distance.java, src/main/java/ywphsm/ourneighbor/service/StoreService.java, src/test/java/ywphsm/ourneighbor/service/ReviewServiceTest.java
SearchController @CookieValue 자료형 String => Double로 변경. 
또한 쿠키값 null인 경우 조건문 리팩토링. 추후에 예외 처리로 코드 보완 예정.
=> Refactor: "SearchController 리팩토링"

src/main/resources/static/css/app.css, src/main/resources/static/js/app.js, src/main/resources/static/js/recommend_post.js, src/main/resources/static/js/slick.js, src/main/resources/templates/index.html, src/main/resources/templates/layout/footer.html
search-top7-random으로 호출한 API 데이터를 출력시킬 프론트 구현 완료.
추후 노출하고자 하는 데이터 보완할 예정.
=> Feature: "무작위 랜덤 추천 API 데이터 출력할 프론트 구현"

src/main/java/ywphsm/ourneighbor/domain/file/AwsS3FileStore.java, src/main/java/ywphsm/ourneighbor/domain/file/CustomMultipartFile.java, src/main/java/ywphsm/ourneighbor/domain/file/FileUtil.java
Imgscalr 라이브러리를 활용하여 업로드 이미지 리사이징 기능 구현.
S3에 업로드하는 이미지 용량도 줄이고 서버에서 해당 이미지를 출력할 때
들어가는 부하 역시 줄어드는 이점을 가질 수 있음.
=> Feature: "이미지 업로드 시 이루어지는 리사이징 기능 구현"

src/main/java/ywphsm/ourneighbor/domain/file/AwsS3FileStore.java, src/main/java/ywphsm/ourneighbor/domain/file/UploadFile.java, src/main/java/ywphsm/ourneighbor/service/MenuService.java, src/main/java/ywphsm/ourneighbor/service/StoreService.java
메뉴판 별도 처리 구현 과정에서 버그 발생하여 이를 수정함.
=> Fix: "매장, 리뷰 등록 시 이미지 리사이징 적용 안 되는 문제 수정"

src/main/java/ywphsm/ourneighbor/domain/file/AwsS3FileStore.java, src/main/java/ywphsm/ourneighbor/domain/file/CustomMultipartFile.java, src/main/java/ywphsm/ourneighbor/domain/file/UploadFile.java, src/main/java/ywphsm/ourneighbor/service/MenuService.java, src/main/java/ywphsm/ourneighbor/service/ReviewService.java, src/main/java/ywphsm/ourneighbor/service/StoreService.java, src/main/resources/static/js/menu.js, src/main/resources/templates/menu/edit_form.html
기능 구현"
s3Client의 deleteObject 기능을 사용하여 S3 Bucket 내부의 파일까지 함께 삭제될 수 있게 기능 변경. 보다 S3 스토리지를 효율적으로 사용할 수 있게 됐음.
=> Feature: "이미지 연관 게시글 삭제 시, S3에 있는 이미지도 함께 삭제되는

src/main/java/ywphsm/ourneighbor/domain/file/CustomMultipartFile.java, src/main/java/ywphsm/ourneighbor/domain/file/FileUtil.java, src/main/java/ywphsm/ourneighbor/service/MenuService.java, src/main/resources/static/js/menu.js, src/main/resources/templates/member/login_form.html
1. 이미지 미등록시 자동으로 설정되는 DefaultImg 등록에 버그가 발생하여 수정. js 단에서 생성한 DefaultImg File이 src를 포함하지 않아 리사이징 과정에서 에러가 발생하는 문제로, 리사이징 메소드 실행 조건에 defaultImg가 인 경우를 제외시킴으로써 해결함.
2. PNG 이미지를 등록 시, ImageIO.wrtie가 False를 반환하고, 빈 데이터가 업로드되는 현상 수정.
Issue Number: #249, # 254
=> Fix: "이미지 등록시 발생하는 버그 2가지 수정"

src/main/java/ywphsm/ourneighbor/domain/store/Store.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepository.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/test/java/ywphsm/ourneighbor/api/ProfileControllerTest.java, src/test/java/ywphsm/ourneighbor/api/ProfileControllerUnitTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/StoreRepositoryTest.java
@DataJpaTest 애노테이션을 활용한 슬라이스 테스트 작성.
모든 테스트 코드 리팩토링 시작.
=> Test: "StoreRepository 테스트 작성 (슬라이스 테스트)"

src/main/java/ywphsm/ourneighbor/api/SearchController.java, src/main/java/ywphsm/ourneighbor/domain/store/Store.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepository.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryCustom.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/main/java/ywphsm/ourneighbor/service/MenuService.java, src/main/java/ywphsm/ourneighbor/service/StoreService.java, src/test/java/ywphsm/ourneighbor/spatial/GeolatteTest.java, src/test/java/ywphsm/ourneighbor/spatial/JTSTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/StoreRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/service/StoreServiceTest.java
매장 저장 시, Point 입력을 위도 경도 순으로 입력받고 있는 문제가 있어 경도, 위도 순으로 변경함.
이에 맞춰 테스트 코드 또한 수정하여 다시 작성.
=> Refactor: "Point입력을 경도, 위도 순으로 변경 및 StoreRepository 테스트 코드 수정"

src/main/java/ywphsm/ourneighbor/api/SearchController.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryCustom.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/test/java/ywphsm/ourneighbor/service/CategoryServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/StoreRepositoryTest.java
범위 내 존재하는 매장을 카테고리로 조회하는 기능에 관한 테스트 코드
작성.
=> Test: "StoreRepositoryTest - 범위 내 매장 카테고리로 조회 테스트 추가"

src/main/java/ywphsm/ourneighbor/repository/member/MemberRepository.java, src/main/resources/static/js/mask.js, src/main/resources/templates/layout/footer.html, src/main/resources/templates/layout/header.html
설정 파일에 server.compression.enabled=true 추가.
meta 태그에 description, viewport 속성 추가로 보다 모바일 친화적이게 개선.
=> Refactor: "html meta 태그 추가 및 텍스트 파일 압축 전송 구현"

src/test/java/ywphsm/ourneighbor/unit/repository/CategoryRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/HashtagRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/MenuRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/StoreRepositoryTest.java
문자열을 그냥 입력한 부분들 getter 활용하는 방식으로 변경  및 단언 부분 hasSize 추가하여 테스트 기능 보완.
=> Refactor: "Repository 테스트 전체 리팩토링"

src/main/java/ywphsm/ourneighbor/api/CategoryApiController.java, src/main/java/ywphsm/ourneighbor/domain/dto/category/CategoryDTO.java, src/main/java/ywphsm/ourneighbor/repository/category/CategoryRepository.java, src/main/java/ywphsm/ourneighbor/service/CategoryService.java, src/test/java/ywphsm/ourneighbor/service/CategoryServiceTest.java, src/test/java/ywphsm/ourneighbor/service/HashtagServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/CategoryRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/service/CategoryServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/StoreServiceTest.java
CategoryService 관한 Unit Test 작성 완료.
=> Test: "CategoryService Unit Test 작성"

src/main/resources/static/js/app.js, src/main/resources/static/js/menu.js, src/main/resources/static/js/recommend_post.js, src/main/resources/templates/recommend_post/add_form.html
추천 양식 등록 시, js단에서 Validation 구현.
=> Feature: "RecommendPost 등록 시 Validation 구현"

src/main/java/ywphsm/ourneighbor/domain/dto/store/StoreDTO.java, src/main/resources/templates/member/sign_up_form.html, src/test/java/ywphsm/ourneighbor/unit/repository/HashtagRepositoryTest.java, src/test/java/ywphsm/ourneighbor/unit/repository/MenuRepositoryTest.java
placeholder 수정 및 제목 매칭이 잘못된 부분 수정.
=> Refacotr: "sign_up_form.html 수정"

src/main/resources/static/js/recommend_post.js, src/main/resources/static/js/review.js, src/main/resources/templates/store/detail.html
주석 처리 해뒀던 줌 기능의 주석을 해제하여 정상적으로 동작되게 구현
=> Refactor: "메뉴판 이미지 모달 줌 기능 다시 되게 변경"

src/main/java/ywphsm/ourneighbor/service/ReviewService.java
Store 엔티티 수정으로 인해 새로 생성된 average 컬럼이 누락되어 이를
추가하여 버그를 해결함.
=> Fix: "rating_average 컬럼이 누락되어 이를 추가함."

src/main/java/ywphsm/ourneighbor/controller/StoreController.java, src/main/java/ywphsm/ourneighbor/domain/store/StoreUtil.java
브레이크타임이 없는 경우 오픈 상태가 null로 보이는 버그 수정.
=> Fix: "매장 오픈 상태 체크 버그 수정"

README.md
=> Docs: "Readme.md 수정"

appspec.yml, scripts/health.sh, scripts/profile.sh, scripts/start.sh, scripts/stop.sh, scripts/switch.sh
=> Docs: "script파일, appspec.yml 파일 수정"

src/main/resources/static/css/app.css, src/main/resources/static/css/argon.css
=> Style: "checkbox 색 변경"

src/main/java/ywphsm/ourneighbor/api/SearchController.java
private static final를 활용한 기호 상수로 거리 변수 값을 변경시킴.
=> Refactor: "SearchController 거리 변수 기호 상수로 변경"

src/main/resources/templates/store/list.html
=> Style: "날씨 기반 매장 추천 List 헤더 생성"

src/main/resources/templates/member/login_form.html
=> Style: "login_form.html css 수정"

src/main/resources/static/css/app.css, src/main/resources/templates/member/login_form.html
header를 지우고 section 자체를 flex로 만들어 정중앙 정렬을 구현.
=> Style: "logn_form 가운데 정렬 구현"

src/main/java/ywphsm/ourneighbor/api/SearchController.java
SearchController에 반복되는 조회 로직이 존재하여 이를 메소드 추출을 통한 리팩토링을 실시함.
=> Refactor: "조회한 매장의 상태와 거리를 조회하는 로직을 별도의 메소드로 추출"

src/main/resources/templates/member/sign_up_form.html
validation을 담당할 div 2개를 정상적으로 등록하여 이를 해결
=> Fix: "phoneNumber Valid 태그 부재로 인하여 회원가입 실패 버그 수정"

src/main/resources/static/css/app.css, src/main/resources/templates/member/sign_up_form.html
전화번호 검증 div가 우측으로 치우쳐져 이를 수정함.
=> [Style] Validation 스타일 무너진 부분 수정

src/main/resources/static/css/app.css
특정 부분의 css 코드가 망가졌으나 찾지 못하여 기존 코드로 백업함.
=> Style: "app.css 코드 망가짐으로 인하여 백업"

src/main/resources/static/css/app.css, src/main/resources/templates/layout/navbar.html
=> Style: "navbar 폰트 크기 수정 및 Air 폰트 굵기 수정"

src/main/java/ywphsm/ourneighbor/api/SearchController.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryCustom.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/main/java/ywphsm/ourneighbor/service/store/StoreService.java, src/test/java/ywphsm/ourneighbor/unit/repository/StoreRepositoryTest.java
기존 매장 키워드 검색은 전 범위에 걸쳐서 데이터가 조회됐기에 거리 조건을
부여하여 이를 원하는 조건에 맞게 검색될 수 있게 변경.
=> Feature: "매장 키워드 검색 시 거리 기반 조건 부여"

src/main/java/ywphsm/ourneighbor/api/SearchController.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryCustom.java, src/main/java/ywphsm/ourneighbor/repository/store/StoreRepositoryImpl.java, src/main/java/ywphsm/ourneighbor/service/store/StoreService.java, src/main/resources/templates/map.html
기존 카테고리 조회 시, 전체 데이터를 불러온 후 거리값에 대한 필터링을
적용했으나 hibernate spatial을 이용하여 조회 쿼리에서부터 거리 조건을
부여하여 조회할 수 있게 변경.
=> Feature: "map.html에서 카테고리로 조회 시, 거리 기반 조건 부여"

src/test/java/ywphsm/ourneighbor/unit/service/CategoryServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagOfMenuServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagOfStoreServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/RecommendPostServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/StoreServiceTest.java
=> Test: "StoreService 단위 테스트 구현 - 저장 로직"

src/main/java/ywphsm/ourneighbor/service/store/StoreService.java, src/test/java/ywphsm/ourneighbor/unit/service/CategoryServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagOfMenuServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagOfStoreServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/HashtagServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/RecommendPostServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/service/StoreServiceTest.java, src/test/java/ywphsm/ourneighbor/unit/spatial/GeolatteTest.java
단순 매장 정보 수정, 같은 레벨 카테고리 수정, 하위 레벨 카테고리 추가 별 테스트 코드 작성
=> Test: "StoreServiceTest - Update 테스트 코드 작성"
